---
title: Laboratory of Structural Biology
timezone: Asia/Seoul
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
bio: Rm 609, Hana Science Hall-A, </br> Division of Life Sciences, College of Life Sciences and Biotechnology, Korea Univ. </br> 145 Anam-ro, Seongbuk-gu, Seoul 02841, Korea
description: Hyun kyu Song's lab </br> Tel. 02-3290-3553 </br> hksong(a)korea.ac.kr
reading_time: true
words_per_minute: 200
logo: assets/img/lsb.png
background: assets/img/background.jpg
tiled_bg: false
locale: en_US
url: https://song.korea.ac.kr
permalink: "/:title/"
markdown: kramdown
highlighter: rouge
kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  enable_coderay: false
mathjax: true
sass:
  sass_dir: _sass
  style: compressed
disqus_shortname: favorite21-github-io
email: hksong@korea.ac.kr
gems:
- jekyll-mentions
- jekyll-feed
- jekyll-sitemap
- jekyll-gist
jekyll-mentions:
  base_url: https://github.com
exclude:
- README.md
- Gemfile
- Gemfile.lock
- node_modules
- gulpfile.js
- package.json
- _site
- src
- vendor
- CNAME
- LICENSE
- Rakefile
